### ISSUE TITLE
Deployment error in Azure Ubuntu VM

### ISSUE THREAD

**Issue by JPchico** [aiidalab/ansible-role-aiidalab-server#33]
I was trying to deploy the server in an ubuntu 22.04 VM in azure and I got the following error
```
TASK [marvel-nccr.aiidalab_server : pull docker image] ************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'bool' is not iterable
fatal: [aiidalab]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 925, in <module>
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 891, in main
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 595, in __init__
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/basic.py", line 502, in __init__
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 268, in validate
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 236, in validate
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 730, in _validate_sub_spec
      File "/tmp/ansible_docker_image_payload_lwly95gd/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 806, in set_fallbacks
    TypeError: argument of type 'bool' is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ********************************************************************************************************************************************************************************************************
aiidalab                   : ok=29   changed=15   unreachable=0    failed=1    skipped=10   rescued=0    ignored=0   

```

It seems that something goes wrong when it is pulling the docker image for aiidalab?  If I check with the `-vvv` it seems that  it has problems with the ssh connection? Which seems quite strange since it seems to be able to do the rest of the operations. Which leads me to believe that the problem is something else.

I tried deploying another VM with ubuntu 18.4 to test if the issue is related with the OS version and then I found the following error:
```
TASK [marvel-nccr.aiidalab_server : pull docker image] ************************************************************************************************************************************************************
fatal: [aiidalab]: FAILED! => changed=false 
  module_stderr: |-
    /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (3.0.4) doesn't match a supported version!
      RequestsDependencyWarning)
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 48, in invoke_module
      File "/usr/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 925, in <module>
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py", line 897, in main
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 601, in __init__
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/basic.py", line 502, in __init__
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 268, in validate
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/arg_spec.py", line 239, in validate
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 730, in _validate_sub_spec
      File "/tmp/ansible_docker_image_payload_320i9i0q/ansible_docker_image_payload.zip/ansible/module_utils/common/parameters.py", line 806, in set_fallbacks
    TypeError: argument of type 'bool' is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ********************************************************************************************************************************************************************************************************
aiidalab                   : ok=32   changed=22   unreachable=0    failed=1    skipped=8    rescued=0    ignored=0 
```

The error now seems to be the version of certain python libraries, for what I can see. 

Any suggestions on what could solve this issue? 

I think having support for 20.04 would be very good since 18.04 since next year it is scheduled to be in the end of standard support.

**Comment by ltalirz** [comment]
@csadorf @yakutovicha

**Comment by yakutovicha** [comment]
@JPchico, thanks for the report. I just tried to rerun the role, and it seemed to work on my machine. Can you share your ansible version, so we can try to investigate the issue?

For your information, the aiidalab host I tried to run is Ubuntu 20.04.

Here is the output of `ansible --version`:
```
```

**Comment by ltalirz** [comment]
note that this may be using https://github.com/aiidalab/ansible-playbook-aiidalab-server
please check whether the way this playbook uses the role still works

**Comment by JPchico** [comment]
Sorry yes! I just now realize that the repo name is different got a bit
confused. But Leopold is right I'm using the playbook.

I'm currently ill so I can't check it now but I'll try to do it tomorrow.

**Comment by yakutovicha** [comment]
> note that Jonathan may be using https://github.com/aiidalab/ansible-playbook-aiidalab-server please check whether the way this playbook uses the role still works

oh, thanks @ltalirz for clarifying. I will have a look at https://github.com/aiidalab/ansible-playbook-aiidalab-server. I think it was not updated for a while and needs a revision.

**Comment by JPchico** [comment]
Hi @yakutovicha I have managed to checked the ansible version as you suggested
```
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/home/jonathan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jonathan/anaconda3/envs/aiidalab_server/lib/python3.9/site-packages/ansible
  ansible collection location = /home/jonathan/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jonathan/anaconda3/envs/aiidalab_server/bin/ansible
  python version = 3.9.12 (main, Jun  1 2022, 11:38:51) [GCC 7.5.0]
  jinja version = 3.1.2
  libyaml = True
```

I also wonder if I should move this issue to the playbook git instead. Sorry for the confusion, I was a bit ill when I was deploying this and the similar name tripped me up.

**Comment by yakutovicha** [comment]
> I also wonder if I should move this issue to the playbook git instead

I think yes, that would be a better place for the issue. I will move the issue, don't worry.
